spring:
  application:
    name: ITLens

  datasource:
    url: jdbc:postgresql://localhost:5432/itlens
    username: axel
    password: 6631
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
